### ISSUE TITLE
AAT, I'd like a webview test that asserts - 'This page is in this book.'

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#224]
# CASE NUM: C195058
## Section

Show Which Books a Single Page is in

https://trello.com/c/i560M3Af/422-front-end-show-which-books-a-single-page-is-in
Bugs: https://github.com/Connexions/webview/milestone/3

## User story

AAT, I'd like a webview test that asserts - 'This page is in this book.'

## Steps

Can use this link to test: 
https://staging.cnx.org/contents/mjO9LQWq/Slanguage

**Comment by m1yag1** [comment]
@kerwinso The book link used for this test is currently only in one book. Do you think this would change in the future? If another book uses this page it would break this test. How much risk is there for that happening?

**Comment by kerwinso** [comment]
@m1yag1 On staging, it's very unlikely that this page would be added to another book (especially because it's not an OpenStax-authored page). I just needed an example of a page that appears in one book to test that the 'This page is in this book' message and book links appeared. Also, it uses the word 'barf' 😛.

**Comment by m1yag1** [comment]
completed by #245
