### ISSUE TITLE
AAT, I'd like a webview test that asserts Book title link should not be limited in length

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#228]
# CASE NUM: C195061
## Section

Show Which Books a Single Page is in

https://trello.com/c/i560M3Af/422-front-end-show-which-books-a-single-page-is-in
Bugs: https://github.com/Connexions/webview/milestone/3

## User story

AAT, I'd like a webview test that asserts Book title link should not be limited in length

## Steps

1. Go to this link https://staging.cnx.org/contents/BWYBGK7C@2/Executive-Summary
1. Look at the title in the left nav, it should say: 
`"Our Cultural Commonwealth" The Report of the American Council of Learned Societies Commission on Cyberinfrastructure for the Humanities and Social Sciences`

## Expected Result

The title in the left nav should not be cut off or limited to 2 lines. You should be able to read the full title of the book which runs 5 lines long.

**Comment by m1yag1** [comment]
Hey @kerwinso , we need a little more context on this issue. When the text was cut-off was it completely cut-off as in the text wasn't there or was it obscured by another element? The reason I ask is that the test wants to make sure long lines of text are world-wrapped appropriately. There is no way to detect that in selenium. When we use the `.text` attribute it returns the text only.

**Comment by kerwinso** [comment]
@m1yag1 This test originated from this issue: https://github.com/Connexions/webview/issues/1610

When the text was cut off, it was cut off at the second line's end point with an ellipsis `...` and then the rest of the book title would not display. 

**Example:** 
`Programming Fundamentals - A Modular Structured Approach using C++`
became
`Programming Fundamentals - A Modular Structured Approach using...`

Like in this screenshot: https://user-images.githubusercontent.com/253212/38148312-867c56d6-341b-11e8-9e03-fa2580bd34eb.png

This was originally implemented as an aesthetic/design choice. However, we decided to remove the title length limitation altogether, because some important info was being lost in the truncated titles.

So in brief, the acceptance criteria is that the full title of the book should display in the browser with no truncation at all. (I'm not so worried about word-wrapping.) 

I think if you are able to grab the full title in the `.text` attribute in selenium for [the book specified in the test](https://staging.cnx.org/contents/BWYBGK7C@2/Executive-Summary), that should be fine to consider as passing the test.

**Example:**
- `link.text = "Our Cultural Commonwealth" The Report of the American Council of Learned Societies Commission on Cyberinfrastructure for the Humanities and Social Sciences` == PASS
- `link.text = "Our Cultural Commonwealth" The Report of the American Council of Learned...`(or something like this) == FAIL

**Comment by m1yag1** [comment]
@kerwin Ok, so it seems that we could simply look for the ellipsis and if they exist fail the test. would that be a correct test. This would be better than trying to hardcode the title of the book into the test. the test should be able to check any page and run this test.

Essentially that would look like this:
`assert '...' not in book.title`

**Comment by kerwinso** [comment]
@m1yag1 I had thought of that too. Looking into it more, I think `assert '...' not in book.title` will be just fine.

Initially I was hesitant, because I thought, "What if a book has an ellipsis in the title?" But doing a search for `'...'` across all CNX book titles yields zero results, so your proposed test should work: https://cnx.org/search?q=title:...%20type:%22Book%22

**Comment by m1yag1** [comment]
@BrianYing, you can adjust your test to assert that the ellipses doesn't exist. 

I will go ahead and unblock this issue.

**Comment by m1yag1** [comment]
#238

**Comment by m1yag1** [comment]
Resolved by #238
