### ISSUE TITLE
AAT, I'd like a webview test that asserts buggy-looking loading message should not appear in left pane

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#233]
# CASE NUM: C195071
## Section

Show Which Books a Single Page is in

https://trello.com/c/i560M3Af/422-front-end-show-which-books-a-single-page-is-in
Bugs: https://github.com/Connexions/webview/milestone/3

## User story

AAT, I'd like a webview test that asserts buggy-looking loading message should not appear in left pane

## Steps

1. Go to this link https://staging.cnx.org/contents/yWshIYVW/How-Changes-in-the-Cost-of-Liv
1. Watch the left pane closely.

## Expected Result

As the page loads, there should _not_ be a message 'This page is in books' in the left pane without any links to books. If there is, it's a regression.

**Comment by m1yag1** [comment]
@kerwinso A quick question: the bug in this test case is when there are no books listed right?

**Comment by kerwinso** [comment]
@m1yag1 @BrianYing  In this case, there _should_ be a book listed in the left pane, because this page does belong to a book.

This is how it should look:
![image](https://user-images.githubusercontent.com/11298165/42580907-37cfb510-84f1-11e8-8a75-eb7fe93fdfce.png)

 

The bug is that in the left pane, the link to the book was taking a long time to load, and in the meantime the left pane was also displaying a 'This page is in books' message (message varies depending on how many books the page is in). 

It would look something like this (which looks like a bug):
![image](https://user-images.githubusercontent.com/11298165/42580831-0ac4838e-84f1-11e8-9ee5-6dc2c87c7684.png)

So I guess the automation would have to check that both the 'This page is in books' message (or equivalent) does not display without link(s) to the books.

**Comment by m1yag1** [comment]
@kerwinso ok so i'm reviewing the test case and this seems to specifically be when the page is loading. That may not be something we can check. All our tests wait for the page to be loaded before doing anything. This may not be something we can automate.

**Comment by kerwinso** [comment]
@m1yag1 That's OK if we can't automate it. It's not a high-priority regression-- just a less-than-optimized user experience that I haven't really been able to reproduce anyway (the screenshot above was Photoshopped based on my memory). 😃

**Comment by kerwinso** [comment]
BTW, here's the original github issue: https://github.com/Connexions/webview/issues/1620

**Comment by m1yag1** [comment]
this is already covered by #245

**Comment by m1yag1** [comment]
This issue is closed to it being very difficult to replicate during automation. It also isn't a high priority regression.
