### ISSUE TITLE
As a tester, I'd like a webview test that asserts REMINDER: check for caching issues (do NOT use private browser)

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#83]
REMINDER: Check for new user-facing features in a browser that has previously cached data from webview -- especially js, css, images. Do NOT use an incognito or private browser. 

The idea is to replicate an end user experience and catch any problems that may arise due to caching issues.

**Comment by Dantemss** [comment]
Reference: https://stackoverflow.com/questions/22685755/retaining-cache-in-firefox-and-chrome-browser-selenium-webdriver

**Comment by Dantemss** [comment]
I see 2 possible solutions for local tests. Will not work on Travis because we cannot persist the cache there.

A: Add a flag (such as `--cache`) and require the tester to run the tests both before and after the deployment with the flag set.

B: Always enable caching by default.

When caching is enabled, we will set the Chrome profile path to a fixed path in the filesystem. That should enable caching. Will require changes to the legacy tests that always assume the user is not logged in at the beginning.

**Comment by Dantemss** [comment]
This answer to a different issue may allow us to specify the profile by name instead of path: https://stackoverflow.com/a/6830109

**Comment by kerwinso** [comment]
😄 This was originally written as just a reminder to the manual tester. But I'm glad we're thinking about caching issues (and how to automate testing them).

**Comment by m1yag1** [comment]
Closing issue as I don't think we'll get around to this anytime soon. We can re-open when the need arises.
